### ISSUE TITLE
please make deploy to heroku button

### ISSUE THREAD

**Issue by raisedhand** [retrontology/vodloader#1]
hi retrontology ,
please if it's possible make deploy to heroku button for free of monthly vps charge. also heroku have any buildpack you need like selenium , chrome headless , ffmpeg or ...
waiting for your response
finest regards

**Comment by retrontology** [comment]
I'm not very familiar with the Heroku platform, but I will look into it and see if it's viable.

**Comment by retrontology** [comment]
Unfortunately in it's current state VODLoader not very "plug and play" friendly. It requires a few user provided files for configuration and doesn't incorporate environmental variables into this process as of yet. It also requires the entire stream be downloaded before it is uploaded, and I'm not sure Heroku supplies the necessary amount of space. Due to this, I won't incorporate a button in the readme at this time. However, it does seem you can create your own app just by providing the github url, so I would recommend going that route at this time.
